[target.wasm32-unknown-unknown]
rustflags = [
  "-Clink-arg=--shared-memory",
  "-Clink-arg=--import-memory",
  "-Clink-arg=--initial-heap=0",
  "-Clink-arg=--max-memory=4294967296",
  "-Clink-arg=--export=__wasm_init_tls",
  "-Clink-arg=--export=__heap_base",
  "-Clink-arg=--export=__tls_size",
  "-Clink-arg=--export=__tls_align",
  "-Clink-arg=--export=__tls_base",
  "-Ctarget-feature=+atomics",
  "-Ctarget-feature=+bulk-memory",
  "-Ctarget-feature=+crt-static",
  "-Ctarget-feature=+exception-handling",
  "-Ctarget-feature=+extended-const",
  "-Ctarget-feature=+multivalue",
  "-Ctarget-feature=+mutable-globals",
  "-Ctarget-feature=+nontrapping-fptoint",
  "-Ctarget-feature=+reference-types",
  "-Ctarget-feature=+relaxed-simd",
  "-Ctarget-feature=+sign-ext",
  "-Ctarget-feature=+simd128",
  "-Ctarget-feature=+tail-call",
  "--cfg=tokio_unstable",
  '--cfg=getrandom_backend="wasm_js"',
  "-Aunused",
]
